added HeaderMenuMobile
npomba/mskacademy.ru pull request #29
Opened 2022-03-16 10:30 UTC by AlexGert42

2022-03-16 11:51 UTC, Novailoveyou requested changes

2022-03-16 11:51 UTC, Novailoveyou commented on components/header/HeaderMenuMobile.tsx
> +        <div className={stls.contscts}>
typo
```suggestion
        <div className={stls.contacts}>
```

2022-03-16 11:51 UTC, Novailoveyou commented on components/header/HeaderMenuMobile.tsx
> +          <IconGeneralCross classNames={[stls.iconCross]}/>
shound be an `a` tag with `IconGeneralCross` inside

2022-03-16 11:51 UTC, Novailoveyou commented on components/header/HeaderMenuMobile.tsx
> +import { dataGeneralMenuLinks } from '@/data/index'
should be above `config`

2022-03-16 11:51 UTC, Novailoveyou commented on styles/components/header/HeaderMenuMobile.module.sass
> +        position: absolute
should be position: fixed

2022-03-16 11:51 UTC, Novailoveyou commented on styles/components/header/HeaderMenuMobile.module.sass
> +    list-style: none
avoid `list-style-type: none`, use `display: flex` on child instead

2022-03-16 11:51 UTC, Novailoveyou commented on styles/components/header/HeaderMenuMobile.module.sass
> +    margin-top: auto
avoid `auto` for vertical margin

2022-03-16 15:13 UTC, Novailoveyou requested changes

2022-03-16 15:13 UTC, Novailoveyou commented on styles/components/header/HeaderMenuMobile.module.sass
> +    @include m.dye(c, c.$psi)
`opacity` property should be dropped, use sass `rgba()` instead
```suggestion
    @include m.dye(c, rgba(c.$psi, .5))
```

2022-03-16 15:13 UTC, Novailoveyou commented on styles/components/header/HeaderMenuMobile.module.sass
> +    display: block
shouldn't be necessary

2022-03-16 15:13 UTC, Novailoveyou commented on styles/components/header/HeaderMenuMobile.module.sass
> +    height: 100vh
`padding`s should be moved to `.container`, `.wrapper` declaration should be dropped

2022-03-16 15:13 UTC, Novailoveyou commented on styles/components/header/HeaderMenuMobile.module.sass
> +    max-width: f.px(48)
it's `24px` in figma

2022-03-16 15:13 UTC, Novailoveyou commented on styles/components/header/HeaderMenuMobile.module.sass
> +    padding: f.px(40) 0
use `margin` instead of `padding` here. It should only be applied to `top` edge

2022-03-16 15:13 UTC, Novailoveyou commented on styles/components/header/HeaderMenuMobile.module.sass
> +    padding: f.px(40) 0
needs to have `border` following figma design

2022-03-16 15:13 UTC, Novailoveyou commented on styles/components/header/HeaderMenuMobile.module.sass
> +    padding-top: f.px(16)
should only have `margin-top`

2022-03-17 11:14 UTC, Novailoveyou requested changes

2022-03-17 11:14 UTC, Novailoveyou commented on components/icons/general/IconGeneralCross.tsx
> +          stroke-width="2"
There is no such property as `stoke-width` in React, use `stokeWidth`instead

2022-03-17 11:14 UTC, Novailoveyou commented on components/icons/general/IconGeneralCross.tsx
> +          stroke-linecap="round"
There is no such property as `stroke-linecap` in React, use `strokeLinecap`instead. React throws a warning in concole about this. Please don't ignore warnings

2022-03-17 11:43 UTC, AlexGert42 commented on styles/components/header/HeaderMenuMobile.module.sass
> +    display: block
what exactly ?

2022-03-17 12:00 UTC, Novailoveyou requested changes

2022-03-25 10:59 UTC, Novailoveyou approved these changes
Approving for now, have to meet deadline. Unaddressed issues I will fix myself

2022-03-25 10:59 UTC, merged